config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  resources :restaurants do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = %w(chinese italian japanese french belgian)
  
  has_many :reviews, dependent: :destroy
  validates :name, :address, presence: true
  validates :category, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating ,numericality: { only_integer: true }
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurant_controller.rb
class RestaurantController < ApplicationControllerend
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render "edit", status: :unprocessable_entity
    end
  end

    def destroy
      @restaurant.destroy
      redirect_to restaurants_path, status: :see_other
    end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render "restaurants/show", status: :unprocessable_entity
    end
  end

    def destroy
      @review = Review.find(params[:id])
      @review.destroy
      redirect_to restaurant_path(@review.restaurant), status: :see_other
    end

  private


  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category, collection: Restaurant::CATEGORY %>
  <%= f.input :phone_number %>
  <%= f.submit class: "btn btn-primary mt-4" %>

  <%#= link_to "Delete", pet_path(Pet.last), data: { turbo_method: :delete, turbo_confirm: "Are your sure?" } %>
  <%#= button_to "Delete", pet_path(Pet.last), method: :delete, form: { data: { turbo_confirm: "Are your sure?" } } %>
<% end %>

app/views/restaurants/edit.html.erb
<div class="container mt-5">
  <h1>Edit <%= @restaurant.name %></h1>

  <%= render "form" %>
</div>

app/views/restaurants/index.html.erb
<div class="container mt-5">
  <h1>All Restaurants</h1>

<%= link_to "Add a Restaurant", new_restaurant_path , class: "btn btn-primary mb-5" %>
 <hr>
  <ul class="list-inline">


    <% @restaurants.each do |restaurant| %>

        <li>
          <div class="container">
            <div class="card" style="width: 20rem;">
                <img src="https://source.unsplash.com/random/?restaurant" class="card-img-top" alt="Accroche HTML">
                <div class="card-body">
                    <h2 class="card-title"><%= link_to  restaurant.name  %></h2>

                    <%=link_to "info", restaurant_path(restaurant), class: "btn btn-primary mb-3" %>
                </div>
            </div>
          </div>
        </li>

    <% end %>
  </ul>


</div>


<hr>

app/views/restaurants/new.html.erb
<div class="container mt-5">
  <h1>Add a new restaurant</h1>

  <%= render "form" %>
</div>

app/views/restaurants/show.html.erb
<!--<div class="container mt-5">
  <h1><%= @restaurant.name %> <small>(<%= @restaurant.category %>)</small></h1>
  <ul>
    <li>Address: <%= @restaurant.address %></li>
    <li>phone: <%= @restaurant.phone_number %></li>
  </ul>

  <%= link_to "Edit #{@restaurant.name}", edit_restaurant_path(@restaurant) %>
  <br>
  <%= link_to "Delete #{@restaurant.name}", restaurant_path(@restaurant), data: { turbo_method: :delete, turbo_confirm: "Are your sure?" } %>
  <br>
  <%= link_to "Back to all restaurants", restaurants_path %>
</div>-->



    <div class="container">
        <h1><%= @restaurant.name %></h1>
        <div class="cardcontainer">
            <div class="photo">
                <img src="https://source.unsplash.com/random/?restaurant">
                <div class="photos">Photos</div>
            </div>
            <div class="content">
                <p class="txt4"><%= @restaurant.address %></p>
                <p class="txt5">+<%= @restaurant.phone_number %></p>
            </div>
            <div class="footer ">
            <div class="d-flex justify-content-between">
                <p><a class="waves-effect waves-light btn" href="<%=edit_restaurant_path(@restaurant)%>">edit</a> <%= link_to "delete", restaurant_path(@restaurant), data: { turbo_method: :delete, turbo_confirm: "Are your sure?" }, class: "btn btn-warning justify-content-between wrn" %> </div>
                <p class="txt3"><i class="far fa-clock"></i>10 Minutes Ago <span class="comments"><i class="fas fa-comments"></i>45 Comments</span></p>
                <%=  %>
            </div>
        </div>
    </div>

<%=simple_form_for [@restaurant, @review ] do |f|%>
                  <%= f.input :content %>
                  <%= f.input :rating, collection: 0..5 %>
                  <%= f.submit%>
                  <%end %>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>